version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: satstyler-sqlitebrowser
      APP_PORT: 3000
  server:
    container_name: sqlitebrowser
    image: linuxserver/sqlitebrowser:3.13.1@sha256:1b1e81f0af222af3353a4c8d3c4737264a1816a43e4410819430335fa099b1da
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure
